"""Sample tender records for local development and demos."""

from datetime import date, timedelta

from tenders.models import Tender

TODAY = date.today()

SAMPLE_SOURCES = [
    {
        "name": "National Treasury eTenders",
        "slug": "etenders",
        "base_url": "https://www.etenders.gov.za/",
        "scraper_name": "etenders",
    },
    {
        "name": "Tenders-SA",
        "slug": "tenders-sa",
        "base_url": "https://www.tenders-sa.co.za/",
        "scraper_name": "tenders_sa",
    },
]

SAMPLE_TENDERS = [
    {
        "source_slug": "etenders",
        "external_id": "sample-001",
        "title": "Supply and delivery of office furniture for regional offices",
        "description": "Appointment of a service provider for the supply, delivery and installation of office furniture at multiple provincial offices.",
        "department": "Department of Public Works and Infrastructure",
        "category": "Furniture and fittings",
        "tender_type": Tender.TenderType.GOVERNMENT_DEPARTMENT,
        "province": "Gauteng",
        "published_date": TODAY - timedelta(days=5),
        "closing_date": TODAY + timedelta(days=21),
        "url": "https://www.etenders.gov.za/",
    },
    {
        "source_slug": "etenders",
        "external_id": "sample-002",
        "title": "Provision of security guarding services for a 24-month period",
        "description": "Request for proposals for armed and unarmed guarding services, access control, and patrols at government facilities.",
        "department": "South African Police Service",
        "category": "Security services",
        "tender_type": Tender.TenderType.GOVERNMENT_DEPARTMENT,
        "province": "Western Cape",
        "published_date": TODAY - timedelta(days=3),
        "closing_date": TODAY + timedelta(days=14),
        "url": "https://www.etenders.gov.za/",
    },
    {
        "source_slug": "etenders",
        "external_id": "sample-003",
        "title": "Cleaning and hygiene services for municipal buildings",
        "description": "Tender for daily cleaning, deep cleaning, and consumables supply for municipal administration buildings.",
        "department": "City of Tshwane Metropolitan Municipality",
        "category": "Cleaning services",
        "tender_type": Tender.TenderType.MUNICIPALITY,
        "province": "Gauteng",
        "published_date": TODAY - timedelta(days=7),
        "closing_date": TODAY + timedelta(days=5),
        "url": "https://www.etenders.gov.za/",
    },
    {
        "source_slug": "tenders-sa",
        "external_id": "sample-004",
        "title": "Maintenance of ICT infrastructure and helpdesk support",
        "description": "Three-year contract for network maintenance, server support, and end-user helpdesk services.",
        "department": "Eskom Holdings SOC Ltd",
        "category": "Information technology",
        "tender_type": Tender.TenderType.SOCS,
        "province": "Mpumalanga",
        "published_date": TODAY - timedelta(days=10),
        "closing_date": TODAY + timedelta(days=30),
        "url": "https://www.tenders-sa.co.za/",
    },
    {
        "source_slug": "tenders-sa",
        "external_id": "sample-005",
        "title": "Construction of classroom blocks at a TVET campus",
        "description": "Design and build of two classroom blocks including electrical, plumbing, and furniture provision.",
        "department": "Ekurhuleni East TVET College",
        "category": "Construction",
        "tender_type": Tender.TenderType.TVET_COLLEGES,
        "province": "Gauteng",
        "published_date": TODAY - timedelta(days=2),
        "closing_date": TODAY + timedelta(days=45),
        "url": "https://www.tenders-sa.co.za/",
    },
    {
        "source_slug": "etenders",
        "external_id": "sample-006",
        "title": "Supply of medical consumables and PPE",
        "description": "Framework agreement for the supply of medical consumables, surgical gloves, and personal protective equipment.",
        "department": "Department of Health",
        "category": "Medical supplies",
        "tender_type": Tender.TenderType.GOVERNMENT_DEPARTMENT,
        "province": "KwaZulu-Natal",
        "published_date": TODAY - timedelta(days=1),
        "closing_date": TODAY + timedelta(days=3),
        "url": "https://www.etenders.gov.za/",
    },
    {
        "source_slug": "tenders-sa",
        "external_id": "sample-007",
        "title": "Road rehabilitation and pothole repair programme",
        "description": "Appointment of contractors for road rehabilitation, surfacing, and pothole repairs across district routes.",
        "department": "Mangaung Metropolitan Municipality",
        "category": "Civil engineering",
        "tender_type": Tender.TenderType.MUNICIPALITY,
        "province": "Free State",
        "published_date": TODAY - timedelta(days=6),
        "closing_date": TODAY + timedelta(days=18),
        "url": "https://www.tenders-sa.co.za/",
    },
    {
        "source_slug": "etenders",
        "external_id": "sample-008",
        "title": "Catering services for conferences and official events",
        "description": "Panel of caterers for conferences, workshops, and official functions for a period of 36 months.",
        "department": "University of Cape Town",
        "category": "Catering",
        "tender_type": Tender.TenderType.UNIVERSITY,
        "province": "Western Cape",
        "published_date": TODAY - timedelta(days=4),
        "closing_date": TODAY + timedelta(days=12),
        "url": "https://www.etenders.gov.za/",
    },
    {
        "source_slug": "tenders-sa",
        "external_id": "sample-009",
        "title": "Fleet vehicle maintenance and workshop services",
        "description": "Maintenance, repairs, and servicing of a mixed fleet including light delivery vehicles and bakkies.",
        "department": "Transnet SOC Ltd",
        "category": "Automotive",
        "tender_type": Tender.TenderType.SOCS,
        "province": "Gauteng",
        "published_date": TODAY - timedelta(days=8),
        "closing_date": TODAY + timedelta(days=25),
        "url": "https://www.tenders-sa.co.za/",
    },
    {
        "source_slug": "tenders-sa",
        "external_id": "sample-010",
        "title": "Supply and installation of solar PV systems",
        "description": "Design, supply, and installation of grid-tied solar photovoltaic systems at commercial premises.",
        "department": "GreenEnergy Solutions (Pty) Ltd",
        "category": "Renewable energy",
        "tender_type": Tender.TenderType.PRIVATE_COMPANY,
        "province": "Northern Cape",
        "published_date": TODAY - timedelta(days=9),
        "closing_date": TODAY + timedelta(days=35),
        "url": "https://www.tenders-sa.co.za/",
    },
    {
        "source_slug": "etenders",
        "external_id": "sample-011",
        "title": "Audit and assurance services for statutory entities",
        "description": "External audit services for selected public entities for the financial years 2026–2028.",
        "department": "Auditor-General of South Africa",
        "category": "Professional services",
        "tender_type": Tender.TenderType.GOVERNMENT_DEPARTMENT,
        "province": "Gauteng",
        "published_date": TODAY - timedelta(days=12),
        "closing_date": TODAY + timedelta(days=7),
        "url": "https://www.etenders.gov.za/",
    },
    {
        "source_slug": "etenders",
        "external_id": "sample-012",
        "title": "Waste collection and landfill management services",
        "description": "Collection, transport, and disposal of general waste including recycling programmes for residential areas.",
        "department": "eThekwini Metropolitan Municipality",
        "category": "Waste management",
        "tender_type": Tender.TenderType.MUNICIPALITY,
        "province": "KwaZulu-Natal",
        "published_date": TODAY - timedelta(days=11),
        "closing_date": TODAY + timedelta(days=20),
        "url": "https://www.etenders.gov.za/",
    },
]
